language: objective-c
osx_image: xcode9.2
xcode_workspace: HATDeX.xcworkspace
xcode_scheme: HATDeX
xcode_sdk: iphonesimulator11
before_install:
- rvm install "ruby-2.4.3"
- rvm use 2.4.3
install:
- sudo gem install cocoapods
- sudo gem install bundler
- bundle install
- bundle update
script:
- cd HATDeX/
- bundle exec fastlane sign
env:
  global:
  - secure: I7rfw7RtepF7IbLQOo0n5fsFnVjKpTZOGsa5FFktZRSQe6Fhz70nbtE+w+JvEZglSA+Z4USJaAwSiAQjULIXsPcTISWxuz1Y6ZBKCRy3J/T1kFkGe7j3DpfUxUvrZmBdVyEBAuq18Lq8AwsqW3jJZ+s7I4Olf9iQ7W1mNLWm7MkX62Y1WOF+SpEyOnH+9NtU5msRD0aLqsOrtgxtZ4CNCBW1MgeJvVvuhu+LWATjBKWnUYxyFm998+uv5X2dNjKReMyifVAdTbJfVt/pJAzjo6jUoZqqbsyFSpbA+REIqgyS5UefPoIAN1Pvb1lCD/Ky2+KZ8zCFgX5L0sJ/hY4/lEJHWm9sNko6Vaz8tDG0+RLLe0rziRJdUdo1bzuk+zQ93/nSXHiMTCswZKCzdsW+Nd2Uz5gB3pLZcDc9tGMkbEK5VyvpDSsAbRINFgdLMrhEJ9IId7U9gPCFUfig+k+VYbIHvKDtIG220TcSZJhRoH/U/S2bRyLLPhTPB/m2HGuqanP0eXJu/0shkfIbSN95JhrPGbwKEz2Cdd9BlqoBNBHo7geqeIFzA+pkrshGkjJKopfZAsKMG3L09p11d4/Zc/L8zbPWGQLyNkzBU9RiB50atMl2eJCIAT2BvBW1aOk9KAXaGm3iykfoB1AwIfjOkfvkeqCr5p4TXlE1wvyIPGU=
  - secure: ckeMvUUYBrOvCdnuyxg1rsMOZDUib9/6Q6Ro7O0HHbYDGjcflSHxPw3WsYILS+Cm/E8RCLnlaMuNXFeFFIPsIp/foj1BncaIz1XXlXFkZcj8ErEfGMmMa+dWHGy7y/xWS0ctXXatRrxMrdSxNHVnIn7QnuCE6fiUVMy989qLVF4P2UuclBI64Da5/vLuPg46PH3Ud4Vccren+tZ00VrnS3OfjgaEhI1fiUlvMXoc/gCmgmvavJ5xPceergvAryXcWKdtGyJ2O+TshNl0FVj87F5NdMZXMrpAESrDTwBxlfwr/VHyghb+dQJ5aiNZQbdyNi/KyQfzLh9Gau2H3rJQkHPCbNc3LTvyk6j+fMX95q174PbusjJ1LiwyXrrFg4JiAkcXlKctO45e/eFdGGdTRhOrZBdUEBNrW/FqVTVR3smH75zevm8ZbKjygE2Dv4KLbh4gpMMnlsdlJVKVQdm1/rD/BRsbFJpXLKRdK3BWAc1kOqdM4+smew6BZ264x2FPlUFkdh2QWQ9soUrKz10JBRKnTybXmiHOHe8bO6rSnagJ8PYxwmwvFp/jbHxuh6h0GmPYZ9PLOTUbBWEgYzW3ovKAKmUqA1cnXA6Osiv+k9T0l5rG8t6Nnfw9ZL3QvVyVO/tOl8TLFSJ1tGdfY61yipVzBIIgHkdNggkxcJA4Kp4=
